export interface IObjectKeys {
    [key: string]: any;
}

export interface Merchant extends IObjectKeys {
    "creation_time": number,
    "template_merchant_login": string,
    "merchant_login": string,
    "merchant_full_name": string,
    "password"?: string,
    "must_change_pwd"?: boolean,
    "processing_id": string,
    "terminal_id": string,
    "visa_3ds_id"?: string,
    "master_card_3ds_id"?: string,
    "mir_3ds_id"?: string,
    "merchant_url"?: string,
    "merchant_emails": string,
    "payment_page_login"?: string,
    "options"?: string[],
    "currencies"?: string[],
    "default_currency"?: string,
    "back_url"?: string,
    "fail_url"?: string,
    "rules_page_merchant_name"?: string,
    "merchant_inn"?: string,
    "merchant_kpp"?: string,
    "merchant_ogrn"?: string,
    "merchant_actual_address"?: string,
    "merchant_phone"?: string,
    "merchant_feedback_email"?: string,
    "rules_page_login"?: string,
    "rulesInfo"?: object[],
    "custom_user_logins"?: string[],
    "external_fraud_control_enabled"?: boolean,
    "overrided_fraud_control_login"?: string,
    "enabled"?: boolean,
    "sbp_terminal_id"?: string,
    "amex_3ds_id"?: string,
    "jcb_3ds_id"?: string,
    "cup_3ds_id"?: string,
    "mcc"?: string,
    "card_acceptor_code"?:string,
    "agreement_url"?: string,
    "default_language"?: string,
    "locales"?: string,
    "finish_page_login"?: string,
    "use_multi_language_payment_page"?: boolean,
    "signer_token"?: string,
    "callback_token"?: string,
    "callback_signing_type"?: string,
    "show_param_list_mapping"?: string[],
    "show_binding_param_list"?: string[],
    "viewable_merchant_bindings"?: string[],
    "allowed_binding_type"?: string,
    "private_bindings"?: boolean,
    "payment_attempts"?: number,
    "refund_attempts"?: number,
    "overrided_fraud_control_login_enabled"?: boolean,
    "session_timeout_secs"?: number,
    "auto_completion_delay_hours"?: number,
    "callback_type"?: string,
    "callback_addresses"?: string,
    "callback_operations"?: string[],
    "send_client_email"?: boolean,
    "send_merchant_email"?: boolean,
    "callback_headers"?: string,
    "callback_additional_params"?: string,
    "parent_id"?: string,
    "operations_for_payer_notification"?: string[],
    "operations_for_merchant_notification"?: string[],
    "limits"?: object[],
    "processing_fields"?: object[],
    "received_processing_fields"?: object[],
    "verify_purchase_fields"?: object[],
    "return_params_fields"?: object[],
    "return_back_url_params_fields"?: object[],
    "description"?: string,
    "open_token_id"?: string,
    "merchant_additional_param"?: object[],
    "visa_client_app_id"?: string,
    "mastercard_token_requestor_id"?: string,
    "users": User[]
}

export interface User extends IObjectKeys {
    "username": string,
    "password": string
}